version: "3"
services:
  react:
    image: spring-front
    build:
      context: .
    ports:
      - "7080:443"
    networks:
      - reactnet
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/editor.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/editor.terminaldweller.com/fullchain.pem:ro
      - /etc/letsencrypt/live/editor.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/editor.terminaldweller.com/privkey.pem:ro
    # env:
    #   - SERVER_DEPLOYMENT_KIND=test
networks:
  reactnet:
